frame_id: "base_footprint"
subscribe_depth: false
subscribe_rgbd: true
subscribe_rgb: false

# The frame attached to odometry. If empty, rtabmap will subscribe to odom topic to get odometry.
# If set, odometry is got from tf (in this case, a covariance of 1 is used).
odom_frame_id: "odom"
# visual_odometry: false
odom_topic: "odom"

# RTAB-Map's parameters
RGBD/AngularUpdate: 0.01
RGBD/LinearUpdate: 0.01
RGBD/OptimizeFromGraphEnd: false

# Parameter name changed: "Optimizer/Slam2D" -> "Reg/Force3DoF".
# Optimizer/Slam2D: true

Reg/Force3DoF: true

Rtabmap/DetectionRate: 4

# Ignore lower half of the image (floor), that caused bad loop closures
Kp/RoiRatios: "0 0 0 0.3"
# Only add closer, more certain points to the map. Map is a lot cleaner that way
Grid/RangeMax: 1.5

# Detecting ground
Grid/NormalsSegmentation: true

# Otherwise it also detects higher planes and removes them (for example plane on the stair)
Grid/MaxGroundHeight: 0.02
