frame_id: "base_link"
subscribe_depth: false
subscribe_rgbd: true

# The frame attached to odometry. If empty, rtabmap will subscribe to odom topic to get odometry. 
# If set, odometry is got from tf (in this case, a covariance of 1 is used).
# odom_frame_id: "odom"
# visual_odometry: false
odom_topic: "odom"

# RTAB-Map's parameters
RGBD/AngularUpdate: 0.01
RGBD/LinearUpdate: 0.01
RGBD/OptimizeFromGraphEnd: false

Reg/Force3DoF: true
Optimizer/Slam2D: true

Rtabmap/DetectionRate: 4

# Sometimes visual odom is lost, this setting allow it to get back
Rtabmap/StartNewMapOnLoopClosure: true
Odom/ResetCountdown: 1