rate: 10 # (Hz, used for interpolation controller)
controller_list:
  - name: fake_right_arm_controller
    type: $(arg execution_type)
    joints:
      - shoulder_pitch_right
      - shoulder_roll_right
      - elbow_right
      - wrist_right
      - gripper_twist_right
  - name: fake_hand_controller
    type: $(arg execution_type)
    joints:
      - gripper_finger_r_right
      - gripper_finger_l_right
initial: # Define initial robot poses.
  - group: right_arm
    pose: Home
