# max_velocity and max_acceleration has to be lower for simulation, otherwise path is not executed close enough
# and PATH_TOLERANCE_VIOLATED error appears

# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]

# Position limits should be loaded from urdf, I added them here when checking chomp, but they doesn't seem to be necessary.
joint_limits:
  gripper_finger_r_right_joint:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
    # min_position: -0.05
    # max_position: 0.0
  gripper_finger_l_right_joint:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
    # min_position: 0.0
    # max_position: 0.05
  elbow_right_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 1.0
    # Actual value is -2.1, setting 0 is to enforce more natural movement
    # without bending elbow in opposite direction
    min_position: 0
    max_position: 2.1
  gripper_twist_right_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 1.0
    # min_position: -1.570
    # max_position: 1.570
  shoulder_roll_right_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 1.0
    # min_position: -0.800
    # max_position: 1.979
  shoulder_pitch_right_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 1.0
    # min_position: -2.390
    # max_position: 0.489
  wrist_right_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 1.0
    min_position: -1.994
    # Actual value is 1.146, 0.0 to enforce more natrual movement
    max_position: 0
