right_arm:
  # kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  # kinematics_solver_search_resolution: 0.005
  # kinematics_solver_timeout: 0.005
  # position_only_ik: True

  kinematics_solver: bio_ik/BioIKKinematicsPlugin
  kinematics_solver_search_resolution: 0.01
  kinematics_solver_timeout: 0.2
  position_only_ik: False

  # Kinematics solver doesn't support #attempts anymore, but only a timeout.
  # kinematics_solver_attempts: 5
