controller_list:
  - name: arm_position_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - shoulder_pitch_right
      - shoulder_roll_right
      - elbow_right
      - wrist_right
      - gripper_twist_right
