controller_list:
  - name: arm_position_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - shoulder_pitch_right_joint
      - shoulder_roll_right_joint
      - elbow_right_joint
      - wrist_right_joint
      - gripper_twist_right_joint

  - name: gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - gripper_finger_l_right_joint

  # It is also possible to use GripperCommand instead of FollowJointTrajectory
  # It is simpler - it sends only one command - desired position
  # I wasn't able to solve following problems
  # - moveit sends 0 effort and controller doesn't work in gazebo
  # - effort_controllers/GripperActionController oscillated in gazebo
  # (effort controller instead of position is necessary for grasping objects)

  # - name: gripper_controller
  #   action_ns: gripper_action_controller
  #   type: GripperCommand
  #   default: true
  #   joints:
  #     - gripper_finger_l_right_joint
  #   max_effort: 100.0

  #   # other parameters:
  #   # parallel:
  #   # command_joint:
  #   # allow_failure:
