controller_list:
  - name: arm_position_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - shoulder_pitch_right_joint
      - shoulder_roll_right_joint
      - elbow_right_joint
      - wrist_right_joint
      - gripper_twist_right_joint

  - name: gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - gripper_finger_l_right_joint
