planning_plugin: pilz_industrial_motion_planner::CommandPlanner

# The request adapters (plugins) used when planning, ORDER MATTERS
request_adapters: ""

start_state_max_bounds_error: 0.1

# MoveGroup capabilities to load, append sequence capability
capabilities: $(arg capabilities)
  pilz_industrial_motion_planner/MoveGroupSequenceAction
  pilz_industrial_motion_planner/MoveGroupSequenceService

disable_capabilities: $(arg disable_capabilities)
