roomac:
  # Simulation settings for using moveit_sim_controllers
  moveit_sim_hw_interface:
    joint_model_group: right_arm
    joint_model_group_pose: Home
  # Settings for ros_control_boilerplate control loop
  generic_hw_control_loop:
    loop_hz: 300
    cycle_time_error_threshold: 0.01
  # Settings for ros_control hardware interface
  hardware_interface:
    joints:
      # - wheel_left_joint
      # - wheel_right_joint
      # - shoulder_pitch_left_joint
      # - shoulder_roll_left_joint
      # - elbow_left_joint
      # - wrist_left_joint
      # - gripper_twist_left_joint
      - shoulder_pitch_right_joint
      - shoulder_roll_right_joint
      - elbow_right_joint
      - wrist_right_joint
      - gripper_twist_right_joint
    sim_control_mode: 1 # 0: position, 1: velocity
  # Publish all joint states
  # Creates the /joint_states topic necessary in ROS
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  arm_position_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - shoulder_pitch_right_joint
      - shoulder_roll_right_joint
      - elbow_right_joint
      - wrist_right_joint
      - gripper_twist_right_joint
    gains:
      shoulder_pitch_right_joint:
        p: 10
        d: 0
        i: 0.01
        i_clamp: 1
      shoulder_roll_right_joint:
        p: 10
        d: 0
        i: 0.01
        i_clamp: 1
      elbow_right_joint:
        p: 10
        d: 0
        i: 0.01
        i_clamp: 1
      wrist_right_joint:
        p: 10
        d: 0
        i: 0.01
        i_clamp: 1
      gripper_twist_right_joint:
        p: 10
        d: 0
        i: 0.01
        i_clamp: 1
    constraints:
      goal_time: 30.0
      shoulder_pitch_right_joint:
        goal: 0.01
        trajectory: 0.01
      shoulder_roll_right_joint:
        goal: 0.01
        trajectory: 0.01
      elbow_right_joint:
        goal: 0.01
        trajectory: 0.01
      wrist_right_joint:
        goal: 0.01
        trajectory: 0.01
      gripper_twist_right_joint:
        goal: 0.01
        trajectory: 0.01
    state_publish_rate: 25
    allow_partial_joints_goal: True

  gripper_effort_controller:
    type: effort_controllers/JointGroupPositionController
    joints:
      - gripper_finger_r_right_joint
      - gripper_finger_l_right_joint
    gripper_finger_r_right_joint:
      pid:
        p: 100
        d: 0
        i: 0.01
        i_clamp: 1

    gripper_finger_l_right_joint:
      pid:
        p: 100
        d: 0
        i: 0.01
        i_clamp: 1
