roomac:
  # Simulation settings for using moveit_sim_controllers
  moveit_sim_hw_interface:
    joint_model_group: right_arm
    joint_model_group_pose: Home
  # Settings for ros_control_boilerplate control loop
  generic_hw_control_loop:
    loop_hz: 300
    cycle_time_error_threshold: 0.01
  # Settings for ros_control hardware interface
  hardware_interface:
    joints:
      # - wheel_left
      # - wheel_right
      # - shoulder_pitch_left
      # - shoulder_roll_left
      # - elbow_left
      # - wrist_left
      # - gripper_twist_left
      - shoulder_pitch_right
      - shoulder_roll_right
      - elbow_right
      - wrist_right
      - gripper_twist_right
    sim_control_mode: 1 # 0: position, 1: velocity
  # Publish all joint states
  # Creates the /joint_states topic necessary in ROS
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  arm_position_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - shoulder_pitch_right
      - shoulder_roll_right
      - elbow_right
      - wrist_right
      - gripper_twist_right
    gains:
      shoulder_pitch_right:
        p: 10
        d: 0
        i: 0.01
        i_clamp: 1
      shoulder_roll_right:
        p: 10
        d: 0
        i: 0.01
        i_clamp: 1
      elbow_right:
        p: 10
        d: 0
        i: 0.01
        i_clamp: 1
      wrist_right:
        p: 10
        d: 0
        i: 0.01
        i_clamp: 1
      gripper_twist_right:
        p: 10
        d: 0
        i: 0.01
        i_clamp: 1
    constraints:
      goal_time: 30.0
      shoulder_pitch_right:
        goal: 0.01
        trajectory: 0.01
      shoulder_roll_right:
        goal: 0.01
        trajectory: 0.01
      elbow_right:
        goal: 0.01
        trajectory: 0.01
      wrist_right:
        goal: 0.01
        trajectory: 0.01
      gripper_twist_right:
        goal: 0.01
        trajectory: 0.01
    state_publish_rate: 25
    allow_partial_joints_goal: True

  gripper_effort_controller:
    type: effort_controllers/JointGroupPositionController
    joints:
      - finger1_joint
      - finger2_joint
    finger1_joint:
      pid:
        p: 100
        d: 0
        i: 0.01
        i_clamp: 1

    finger2_joint:
      pid:
        p: 100
        d: 0
        i: 0.01
        i_clamp: 1
