min_change_threshold: 0.01 # [rad]
max_speed: 0.6 # [rad/s]

analog_update_delay: 0.007 # [s]

zero_angle_signal_shoulder_pitch: 860
zero_angle_signal_sholder_roll: 280
zero_angle_signal_elbow: 512
zero_angle_signal_wrist: 1450
zero_angle_signal_gripper_twist: 1590
zero_angle_signal_gripper_finger: 650

analog_lower_signal_bound: 500
analog_upper_signal_bound: 2500

analog_lower_signal_bound_wrist: 600
analog_upper_signal_bound_wrist: 2400

digital_lower_signal_bound: 0
digital_upper_signal_bound: 1024

wrist_signal_zero_position: 1509
wrist_signal_90_degrees: 697

publish_joint_states: false

interpolate_movement: true
interpolation_frequency: 15.0

# exact or approximated
# exact - movement duration will be exactly as requested, but interpolation frequency will vary
# approximated - interpolation frequency will be exactly as requested, but movement duration will vary
interpolation_duration_type: exact

# Linear approximate angle to finger distance using these two points
# 0.2rad -> 0.005m
# 1.0rad -> -0.0045m
gripper_angle_to_distance_a: -0.011875
gripper_angle_to_distance_b: 0.007375
