min_change_threshold: 0.01 # [rad]
max_speed: 0.6 # [rad/s]

analog_update_delay: 0.007 # [s]

zero_angle_signal: [850, 320, 512, 1509, 1590, 650]

analog_lower_signal_bound: 500
analog_upper_signal_bound: 2500

analog_lower_signal_bound_wrist: 600
analog_upper_signal_bound_wrist: 2400

digital_lower_signal_bound: 0
digital_upper_signal_bound: 1024

wrist_signal_zero_position: 1509
wrist_signal_90_degrees: 697

publish_joint_states: true

interpolate_movement: true
interpolation_frequency: 15.0

# exact or approximated
# exact - movement duration will be exactly as requested, but interpolation frequency will vary
# approximated - interpolation frequency will be exactly as requested, but movement duration will vary
interpolation_duration_type: exact
