controller_list:
  - name: fake_arm_controller
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_joint
      - wrist_twist_joint
  - name: fake_hand_controller
    joints:
      - left_gripper_joint