version: "3.9"
services:
  roomac:
    image: macorobots/roomac:simulation
    container_name: roomac_laptop
    volumes:
      - roomac_data:/home/roomac/roomac_data
      - type: bind
        source: /dev
        target: /dev
    environment:
      - ROS_MASTER_URI=http://10.42.0.1:11311
      - ROS_IP=10.42.0.160
    network_mode: host
    privileged: true
    command: roslaunch roomac_bringup laptop_mapping_manual.launch

volumes:
  roomac_data:
    external: true
