version: "3.9"
services:
  roomac:
    image: roomac:simulation
    build:
      context: ../
      dockerfile: docker/Dockerfile.simulation

    volumes:
      - roomac_data:/home/roomac/roomac_data
      - type: bind
        source: /dev
        target: /dev
    network_mode: host
    privileged: true

volumes:
  roomac_data:
    external: true
