# First run:
# $ xhost local:root

version: "3.9"
services:
  roomac:
    image: roomac:simulation
    container_name: roomac_simulation
    volumes:
      - ./roomac_data:/home/roomac/roomac_data
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    network_mode: host
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - LIBGL_ALWAYS_SOFTWARE=1
    command: roslaunch roomac_simulation simulation_mapping.launch
