version: "3.9"
services:
  roomac:
    image: macstepien/roomac:simulation
    container_name: dev_roomac_laptop
    build:
      context: ../
      dockerfile: docker/Dockerfile.laptop

    volumes:
      - roomac_data:/home/roomac/roomac_data
      - type: bind
        source: /dev
        target: /dev
      - type: bind
        source: ~/catkin_ws
        target: /home/roomac/catkin_ws
    network_mode: host
    privileged: true

    stdin_open: true # docker run -i
    tty: true # docker run -t
    entrypoint: /bin/bash

volumes:
  roomac_data:
    external: true
