services:
  roomac:
    image: roomac-laptop:latest
    volumes:
      - roomac_data:/home/roomac/roomac_data
      - type: bind
        source: /dev
        target: /dev
      - type: bind
        source: ~/catkin_ws
        target: /home/roomac/catkin_ws
    network_mode: host
    privileged: true

volumes:
  roomac_data:
    external: true