global_costmap:
  plugins:
    - {name: static_map,       type: "costmap_2d::StaticLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  global_frame: map
  robot_base_frame: base_link
  transform_tolerance: 0.2
  update_frequency: 5.0
  publish_frequency: 0.0
  static_map: true
  rolling_window: false

  inflation_layer:
    inflation_radius: 0.55
    cost_scaling_factor: 10.0