publish_debug: true

camera_frame: "camera_up_rgb_optical_frame"
artag_frame: "ar_marker_2"

# Number of gripper position estimates that will be avaraged to get final one
num_of_readings_for_average: 5

# Offset from detected artag at which pointcloud will be split
z_offset_pointcloud_split: -0.05

# Euclidean clustering parameters
cluster_tolerance: 0.05
min_cluster_size: 10
max_cluster_size: 25000

# Offset from end of elbow, at which arm pointcloud should be split to get just gripper
elbow_gripper_offset: 0.2

# Offset_planning_gripper_point", double_t, 0, "Offset from calculated center gripper poisition to point used for planning (gripper_right_grip)
offset_planning_gripper_point: -0.02
