# Correction offset applied to object position [m]
object_position_correction_x: 0.0
object_position_correction_y: 0.0
object_position_correction_z: 0.02

# Simulation picking object manager settings
open_gripper_value: 0.0
closed_gripper_value: 0.05
