# Offset applied to object position as a pre/post gripping position [m]
#! pre gripping position is currently disabled
pre_goal_retraction_x: 0.1
post_goal_retraction_z: 0.08

# Number of retries of each procedure
procedure_retry_threshold: 5

wait_time_move_group_servers: 120.0

move_group_planning_time: 60.0
move_group_planning_attempts: 10
move_group_goal_orientation_tolerance: 0.1
move_group_goal_position_tolerance: 0.01

arm_name: right_arm
base_link_frame: base_footprint
gripper_frame: gripping_right_link
grasping_group_name: hand
home_position_target_name: Home
