# Correction offset applied to object position [m]
object_position_correction_x: 0.0
object_position_correction_y: 0.0
object_position_correction_z: 0.0

# How long to wait for gripper to open/close [s]
open_gripper_wait_time: 0.0
close_gripper_wait_time: 1.0
