roomac:
  # Simulation settings for using moveit_sim_controllers
  moveit_sim_hw_interface:
    joint_model_group: right_arm
    joint_model_group_pose: Home
  # Settings for ros_control_boilerplate control loop
  generic_hw_control_loop:
    loop_hz: 300
    cycle_time_error_threshold: 0.01
  # Settings for ros_control hardware interface
  hardware_interface:
    joints:
      # - wheel_left_joint
      # - wheel_right_joint
      # - shoulder_pitch_left_joint
      # - shoulder_roll_left_joint
      # - elbow_left_joint
      # - wrist_left_joint
      # - gripper_twist_left_joint
      - shoulder_pitch_right_joint
      - shoulder_roll_right_joint
      - elbow_right_joint
      - wrist_right_joint
      - gripper_twist_right_joint
    sim_control_mode: 1 # 0: position, 1: velocity
  # Publish all joint states
  # Creates the /joint_states topic necessary in ROS
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # todo: rename to arm_controller
  arm_position_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - shoulder_pitch_right_joint
      - shoulder_roll_right_joint
      - elbow_right_joint
      - wrist_right_joint
      - gripper_twist_right_joint
    gains:
      shoulder_pitch_right_joint:
        p: 10
        d: 0
        i: 0.01
        i_clamp: 1
      shoulder_roll_right_joint:
        p: 10
        d: 0
        i: 0.01
        i_clamp: 1
      elbow_right_joint:
        p: 10
        d: 0
        i: 0.01
        i_clamp: 1
      wrist_right_joint:
        p: 10
        d: 0
        i: 0.01
        i_clamp: 1
      gripper_twist_right_joint:
        p: 10
        d: 0
        i: 0.01
        i_clamp: 1
    constraints:
      # Fixes GOAL_TOLERANCE_VIOLATED
      stopped_velocity_tolerance: 0.0
      goal_time: 30.0
      shoulder_pitch_right_joint:
        goal: 0.0
        trajectory: 0.0
      shoulder_roll_right_joint:
        goal: 0.0
        trajectory: 0.0
      elbow_right_joint:
        goal: 0.0
        trajectory: 0.0
      wrist_right_joint:
        goal: 0.0
        trajectory: 0.0
      gripper_twist_right_joint:
        goal: 0.0
        trajectory: 0.0
    state_publish_rate: 25
    allow_partial_joints_goal: True

  gripper_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      # only left finger, right is mimicing
      - gripper_finger_l_right_joint

    gains:
      gripper_finger_l_right_joint:
        p: 1000
        d: 0
        i: 0.01
        i_clamp: 1
    constraints:
      stopped_velocity_tolerance: 0.0
      goal_time: 10.0
      gripper_finger_l_right_joint:
        goal: 0.0
        trajectory: 0.0
    state_publish_rate: 25

  # It is also possible to use GripperCommand instead of FollowJointTrajectory
  # It is simpler - it sends only one command - desired position
  # I wasn't able to solve following problems
  # - moveit sends 0 effort and controller doesn't work in gazebo
  # - effort_controllers/GripperActionController oscillated in gazebo
  # (effort controller instead of position is necessary for grasping objects)

  # gripper_controller:
  #   # parameters confirmed with code
  #   type: effort_controllers/GripperActionController
  #   joint: gripper_finger_l_right_joint
  #   # only left finger, right is mimicing
  #   # - gripper_finger_l_right_joint

  #   gains:
  #     gripper_finger_l_right_joint:
  #       p: 5
  #       d: 0
  #       i: 0.01
  #       i_clamp: 1

  #   goal_tolerance: 0.0005
  #   max_effort: 100.0
  #   stall_velocity_threshold: 0.001
  #   stall_timeout: 1.0
