# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  finger1_joint:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  finger2_joint:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  right_elbow:
    has_velocity_limits: true
    max_velocity: 0.7
    has_acceleration_limits: true
    max_acceleration: 0.1
  right_gripper_twist:
    has_velocity_limits: true
    max_velocity: 0.7
    has_acceleration_limits: true
    max_acceleration: 0.1
  right_shoulder_lift:
    has_velocity_limits: true
    max_velocity: 0.7
    has_acceleration_limits: true
    max_acceleration: 0.1
  right_shoulder_pan:
    has_velocity_limits: true
    max_velocity: 0.7
    has_acceleration_limits: true
    max_acceleration: 0.1
  right_wrist:
    has_velocity_limits: true
    max_velocity: 0.7
    has_acceleration_limits: true
    max_acceleration: 0.1