# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: right_arm
  joint_model_group_pose: Home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - left_wheel
    - right_wheel
    - left_shoulder_pan
    - left_shoulder_lift
    - left_elbow
    - left_wrist
    - left_gripper_twist
    - right_shoulder_pan
    - right_shoulder_lift
    - right_elbow
    - right_wrist
    - right_gripper_twist
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []