name: Build and push docker image

on:
  workflow_call:
    inputs:
      postfix:
        required: true
        type: string
      tag_main_image:
        required: true
        type: boolean
  workflow_dispatch:
    inputs:
      postfix:
        description: "Postfix added to docker image name"
        required: true
        type: string
      tag_main_image:
        description: "Additionally tag image with main tag roomac:simulation"
        required: true
        type: boolean

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set docker image tags
        env:
          TAG_MAIN_IMAGE: ${{ inputs.tag_main_image }}
          IMAGE_POSTFIX: ${{ inputs.postfix }}
        run: |
          if ${TAG_MAIN_IMAGE} == true; then
            echo "TAGS=macorobots/roomac:simulation,macorobots/roomac:simulation-${IMAGE_POSTFIX}" >> $GITHUB_ENV
          else
            echo "TAGS=macorobots/roomac:simulation-${IMAGE_POSTFIX}" >> $GITHUB_ENV
          fi
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ./docker/Dockerfile.simulation
          push: true
          tags: ${{ env.TAGS }}
