name: PR pipeline
on:
  pull_request:
    branches: master
    types: [closed]

jobs:
  industrial-ci:
    if: ${{ github.event.pull_request.merged == true }}
    uses: macstepien/roomac_ros/.github/workflows/industrial_ci_action.yml@master
    with:
      name: ${{ needs.get-bump.outputs.bump }}

  get-bump:
    needs: industrial-ci
    name: Get version bump
    runs-on: ubuntu-latest
    outputs:
      bump: ${{ steps.get-version-bump.outputs.bump }}
    steps:
      - name: Get version bump
        id: get-version-bump
        uses: husarion-ci/action-get-version-bump@v0.2.0

  catkin-release:
    needs: get-bump
    if: ${{ needs.get-bump.outputs.bump != '' }}
    uses: macstepien/roomac_ros/.github/workflows/catkin_release.yml@master
    with:
      name: ${{ needs.get-bump.outputs.bump }}

  build-and-push-docker-image:
    needs: catkin-release
    uses: macstepien/roomac_ros/.github/workflows/build_and_push_docker_image.yml@master
    with:
      postfix: ${{ needs.catkin-release.outputs.new_version }}
      tag_main_image: true
